# Generated by Django 5.1.7 on 2025-03-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_repost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
