# Generated by Django 5.1.7 on 2025-03-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_repost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
