# Generated by Django 5.1.7 on 2025-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('comment', 'Comment'), ('reply', 'Reply'), ('like', 'Like'), ('follow', 'Follow')], max_length=30),
        ),
    ]
