# Generated by Django 5.1.7 on 2025-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.CharField(default='You have a new notification', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('comment', 'Comment'), ('reply', 'Reply'), ('like', 'Like'), ('follow', 'Follow'), ('visit', 'Profile Visit')], max_length=30),
        ),
    ]
