# Generated by Django 5.1.7 on 2025-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_notification_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('mention', 'Mention'), ('comment', 'Comment'), ('reply', 'Reply'), ('like', 'Like'), ('follow', 'Follow'), ('visit', 'Profile Visit')], max_length=30, null=True),
        ),
    ]
