# Generated by Django 5.1.7 on 2025-04-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_followrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='to_user',
            new_name='owner',
        ),
    ]
