# Generated by Django 5.1.7 on 2025-05-19 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 19), null=True),
        ),
    ]
