# Generated by Django 5.1.7 on 2025-05-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('mention', 'Mention'), ('comment', 'Comment'), ('reply', 'Reply'), ('like', 'Like'), ('follow', 'Follow'), ('visit', 'Profile Visit'), ('post_view', 'Post View'), ('story_view', 'Story View'), ('saved_post', 'Post Saved'), ('tagged', 'Tagged in a Post'), ('shared', 'Post Shared'), ('messages', 'Messages')], max_length=30, null=True),
        ),
    ]
